# Welcome to Jekyll!

# Website settings
title: "Raphael Augustos"
description: "Augustos blog, let's share ideas."
keywords: "augustos,raphael,blog,jekyll,github,advpl,js,html5,javascript,php,microsiga,protheus,laravel"

baseurl: "/"
url: "http://www.raphaelaugustos.tk"
# url: "http://192.168.10.10:4000"

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# author
author:
  name: 'Raphael Augustos'
  first_name: 'Raphael'
  last_name: 'Augustos'
  email: 'augustos.raphael@gmail.com'
  facebook_username: 'raugustos'
  github_username: 'raphaelaugustos'
  head_img: 'static/img/landing/Jack.jpg'

# social link
jingyu:
  first_name: 'Raphael'
  last_name: 'Augustos'
  description: 'Developer.'
  link: 'http://angular.jack003.com'
  email: '805963294@qq.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
project:
  ccee:
    name: 'CCEE'
    url: '/Jack614/saplatform'
    img: 'static/img/landing/saplatform.jpg'
  cnpem:
    name: 'CNPEM'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/jekyll.jpg'
  sitel:
    name: 'SITEL'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.jpg'
  sigagpe:
    name: 'SIGAGPE'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.jpg'
  sigajuri:
    name: 'SIGAJURI'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.jpg' 
  dimep:
    name: 'DIMEP'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.jpg'
  nfe:
    name: 'nfe'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/nfe.jpg'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: raugustos
  public_key: q6b0Pv71edrQ3dd6hyqTmnOD8RmPfhEkFkDAYUnyRWv6pKnO5wDT60MOno3C2Gb6


# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-82127723-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
